builds:
  - binary: bin2
    main: ./cmd/bin2/main.go
    goos:
      - windows
      - darwin
      - linux
      - openbsd
      - freebsd
    goarch:
      - 386
      - amd64
      - arm
      - arm64
    goarm:
      - 5
      - 6
      - 7
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

archives:
  - files:
      - none*
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}{{ if .Arm }}v{{ .Arm }}{{ end }}{{ if .Mips }}_{{ .Mips }}{{ end }}"
